name: Rust

on:
  push:
    paths: [ "backend/**", ".github/workflows/rust.yml" ]
    
  pull_request:
    paths: [ "backend/**", ".github/workflows/rust.yml" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Run tests
      run: cargo test --verbose
